### PR TITLE
Adding RethinkDB 2.1.4 Dockerfiles

### PR DESCRIPTION
**Pull request by dalanmiller**

### CODE REVIEW

**Comment by dalanmiller** [comment]
Hey @stuartpb did I do this correctly and would you mind getting this merged sometime today if you're free?

**Comment by stuartpb** [comment]
If you can squash this down to one "Add 2.1.4" commit, I'll merge it.

It looks like you had some trouble with the script - do you know what was causing that?

**Comment by dalanmiller** [comment]
I'm not sure, I was following your instructions and ran the script as so on OS X while in the root of the repo:

```
./cut-new-release.sh 2.1.4
```

I've squashed the commits into one.

**Comment by stuartpb** [comment]
> ran the script as so on OS X

There's the problem. This script was written for the GNU/Linux environment of my Cloud9 workspace: [the BSD `sed` used by OS X doesn't support the `-i` flag the way I use it in the script](http://unix.stackexchange.com/questions/13711/differences-between-sed-on-mac-osx-and-other-standard-sed).

**Comment by dalanmiller** [comment]
Awesome, the files I outputted are the same as the script, no?

**Comment by dalanmiller** [comment]
Hey just pinging you on this @stuartpb, mind if we merge this and fix the `sed` issue in another PR?

**Comment by timstott** [comment]
@dalanmiller @stuartpb Thanks for doing this :clap:

**Comment by stuartpb** [comment]
Just meged this (wanted to clean up the commit message first).

**Pull request closed without merging**
