### PR TITLE
ENTRYPOINT+CMD+entrypoint.sh: best of both worlds (take 2)

### PR DESCRIPTION
**Pull request by anapsix**
Take 2: Using ENTRYPOINT with CMD allows for easier passing of additional arguments to container

After being educated over at docker-library/official-images#692, I'd like to revisit using ENTRYPOINT+CMD in Dockerfile to better arg parsing..  
Using a simple enough _entrypoint.sh_, we can support both use cases:
* `docker run -it rethinkdb --help`: whenever first argument starts with "-", such as "--help" it will act same as passing them to _rethinkdb_ outside of container
* `docker run -it rethinkdb bash`: launches _bash_, likewise whenever first argument does NOT start with "-", _entrypoint.sh_ will assume it's executable binary and will try to launch it.  

This works:
```
$ docker run -it rethinkdb echo "hello thinkers"
hello thinkers
```

And this works:
```
$ docker run -it rethinkdb-test --help
Running 'rethinkdb' will create a new data directory or use an existing one,
  and serve as a RethinkDB cluster node.
[snip]
```

And so does this:
```
$ docker run -it rethinkdb-test --bind all --join rdb1.rethinkdb.org:29015
Recursively removing directory /data/rethinkdb_data/tmp
Initializing directory /data/rethinkdb_data
Running rethinkdb 2.0.1~0jessie (GCC 4.9.1)...
Running on Linux 3.13.0-48-generic x86_64
Loading data from directory /data/rethinkdb_data
Listening for intracluster connections on port 29015
Listening for client driver connections on port 28015
Listening for administrative HTTP connections on port 8080
Listening on addresses: 127.0.0.1, 172.17.0.112, ::1, fe80::42:acff:fe11:70%239
Server ready, "155482cef858_ouv" e0b5e9c7-68e5-49c8-ab44-79c514dfa098
Connected to server "rdb1" ffa2fa8c-75dc-4e70-96e9-d18e60541feb
```

### CODE REVIEW

**Comment by stuartpb** [comment]
Yeah I don't really have a lot of time to lay out why this pr is a bad idea so you're better off just maintaining your fork

**Comment by stuartpb** [comment]
also `comtainer () { image=$1; shift; docker run $image $image $@ }` solves this problem without breaking the install base of every user who uses Docker to run `rethinkdb proxy`

**Comment by anapsix** [comment]
@stuartpb, I believe it's fully compatible with current usage pattern and existing users won't notice it..
no worries though.. that's what GitHub is for :stuck_out_tongue_winking_eye:
thanks for all the work so far.

**Comment by stuartpb** [comment]
also if you want to pretend both that I accepted this and that the other official images did the same, put this in your .bashrc:

```bash
docker () {
  args=()
  command=$1
  shift
  while [[ $command = -* ]]; do
    args+=("$command")
    command=$1
    shift
  done
  if [[ $command = run ]]; then
    postargs=()
    image=$1
    shift
    while [[ $image = -* ]]; do
      postargs+=("$image")
      image=$1
      shift
    done
    # run non-official images or word commands normally
    if [[ $image = */* || $1 != -* ]]; then 
      command docker "${args[@]}" "$command" "${postargs[@]}" "$image" "$@"
    else
      command docker "${args[@]}" "$command" "${postargs[@]}" "$image" "$image" "$@"
    fi
  else
     command docker "${args[@]}" "$command" "$@"
  fi
}
```

**Pull request closed without merging**
