### PR TITLE
Add 2.2.0

### PR DESCRIPTION
**Pull request by dalanmiller**
Version 2.2.0  was released yesterday :D 

http://rethinkdb.com/blog/2.2-release/

### CODE REVIEW

**Comment by stuartpb** [comment]
Hang on, something's not right here - it backed up the old files with a "-e" extension. Did you use the latest version of the script, and what OS (Mac again)?
On Nov 12, 2015 6:48 PM, Daniel Alan Miller <notifications@github.com> wrote:



You can view, comment on, or merge this pull request online at:
  https://github.com/stuartpb/rethinkdb-dockerfiles/pull/19

Commit Summary
Add 2.2.0

File Changes

    A
    jessie/2.2.0/Dockerfile
    (23)
  
    A
    jessie/2.2.0/Dockerfile-e
    (23)
  
    A
    trusty/2.2.0/Dockerfile
    (23)
  
    A
    trusty/2.2.0/Dockerfile-e
    (23)
  
    A
    utopic/2.2.0/Dockerfile
    (23)
  
    A
    utopic/2.2.0/Dockerfile-e
    (23)
  
    A
    vivid/2.2.0/Dockerfile
    (23)
  
    A
    vivid/2.2.0/Dockerfile-e
    (23)
  
    A
    wheezy/2.2.0/Dockerfile
    (23)
  
    A
    wheezy/2.2.0/Dockerfile-e
    (23)
  

Patch Links:
https://github.com/stuartpb/rethinkdb-dockerfiles/pull/19.patchhttps://github.com/stuartpb/rethinkdb-dockerfiles/pull/19.diff

**Comment by dalanmiller** [comment]
Hey Stuart, 

This was on OSX again, I saw your commit that said it got it working so I just ran the README instructions this time rather than doing it by hand.

**Comment by stuartpb** [comment]
If so, looks like BSD sed always takes the argument after -i to be the extension - I'll check if explicitly specifying the empty string is GNU compatible (I'd hope so).

**Comment by stuartpb** [comment]
I have to make a connecting flight right now, so it'll be a few minutes.

**Comment by stuartpb** [comment]
Okay, I'm going to just bite the bullet and take the advice from [this][1] Stack Exchange answer:

>If you want to write a portable script, don't use `-i` — it isn't in POSIX. Do manually what sed does under the hood — it's only one more line of code.
>
>    sed -e '…' "$file" >"$file.new"
>    mv -- "$file.new" "$file"

[1]: http://unix.stackexchange.com/a/92907/7733

**Comment by stuartpb** [comment]
Okay, I just pushed cf4f1e49 to supersede this PR.

The new version of cut-new-release.sh from 94061bb sidesteps the entire in-place editing issue (which was arguably the right way to do it in the first place), so try it again next time - it should work, even on BSDs.

**Comment by stuartpb** [comment]
docker-library/official-images#1183

**Comment by dalanmiller** [comment]
Thank you much @stuartpb!

**Pull request closed without merging**
